name: Signaler une anomalie
description: Signaler un comportement incorrect de CESIZen
title: "[Anomalie] "
labels:
  - "type: anomalie"

body:
  - type: textarea
    id: description
    attributes:
      label: Description de l’anomalie
      description: Décrivez clairement le problème rencontré.
    validations:
      required: true

  - type: dropdown
    id: environnement
    attributes:
      label: Environnement concerné
      options:
        - Développement
        - Recette
        - Production
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Ouvrir la page...
        2. Cliquer sur...
        3. Constater...
    validations:
      required: true

  - type: textarea
    id: resultat_attendu
    attributes:
      label: Résultat attendu
    validations:
      required: true

  - type: textarea
    id: resultat_obtenu
    attributes:
      label: Résultat obtenu
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact estimé
      options:
        - Bloquant
        - Majeur
        - Mineur
    validations:
      required: true